# This package uses some RISCV defines from the sysroot "elf.h"
# These defines are not available in the old sysroot
c_stdlib_version:          # [linux]
  - 2.34                   # [linux]
c_compiler:                # [linux]
  - clang                  # [linux]
cxx_compiler:              # [linux]
  - clangxx                # [linux]
c_compiler_version:        # [linux]
  - 17                     # [linux]
cxx_compiler_version:      # [linux]
  - 17                     # [linux]
